name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21d
    - name: Grant execute permission for build.sh
      run: chmod +x build.sh
    - name: Build
      run: ./build.sh
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: libpng 
        path: ./*
